stages:
  data-download:
    cmd: kaggle competitions download -c nlp-getting-started && unzip nlp-getting-started.zip
      -d raw
    outs:
    - raw
  data-split:
    cmd: python data_split.py
    deps:
    - data_split.py
    - raw/train.csv
    outs:
    - data
