stages:
  data-download:
    cmd: kaggle competitions download -c nlp-getting-started && unzip nlp-getting-started.zip
      -d raw
    outs:
    - raw
  data-split:
    cmd: python data_split.py
    deps:
    - data_split.py
    - raw/train.csv
    outs:
    - data
  training:
    cmd: papermill bert_fine_tuning_training.ipynb bert_fine_tuning_training.ipynb
    metrics:
    - test_metrics.json:
        cache: false
    - train_metrics.json:
        cache: false
    - val_metrics.json:
        cache: false
    deps:
    - bert_fine_tuning_training.ipynb
    - data
    params:
    - batch_size
    - lr
    - n_epochs
