stages:
  data-download:
    cmd: kaggle competitions download -c nlp-getting-started && unzip nlp-getting-started.zip
      -d raw
    outs:
    - raw
  data-split:
    cmd: python data_split.py
    deps:
    - data_split.py
    - raw/train.csv
    outs:
    - data
  training:
    cmd: papermill tf_idf_training.ipynb tf_idf_training.ipynb
    metrics:
    - test_metrics.json:
        cache: false
    - train_metrics.json:
        cache: false
    - val_metrics.json:
        cache: false
    deps:
    - data
    - tf_idf_training.ipynb
